#!/usr/bin/env zsh

RC_FILE="~/.zshrc"
if [ $(uname) = "Linux" ]; then
    color_opt="--color=tty"
fi
if [ -f "$HOME/.shell/common" ]; then
    source "$HOME/.shell/common"
fi

bindkey -v
bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward
zstyle -e ':completion::*:*:*:hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'
bindkey '^?' backward-delete-char
bindkey '^[[7~' beginning-of-line
bindkey '^[[8~' end-of-line

#include custom zsh setup
if [ -f $HOME/.zsh/custom ]; then
    source $HOME/.zsh/custom
fi

# 10ms for key sequences
KEYTIMEOUT=1
