#!/bin/bash

os_type=$(uname)

export PAGER="less -S"
export MANPAGER=$PAGER
export EDITOR=vim

unset USERNAME
export PATH="$HOME/bin:$PATH"

# ls aliases
export CLICOLOR=1
alias lh="ls -alh $color_opt"
alias l.="ls -dF $color_opt .*"
alias l.l="ls -dlF $color_opt .*"
alias ls="ls -F $color_opt"
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias nosetests='nosetests --with-progressive'
alias nt=nosetests
alias virc="vim $RC_FILE; source $RC_FILE"
alias vivi='vim ~/.vimrc'
alias vigit='vim ~/.gitconfig'
alias apt='aptitude'


alias rabbit='sudo -u rabbitmq -H rabbitmqctl'

#lots of manpages use invalid utf-8 chars
#alias man="LANG=en_US.latin1 man"
alias rgrep="grep -R -n --color=auto"
alias white="perl -i -pe 's/\s+$/\n/;s/^\t/    /g'"

alias sls="screen -ls"
