#!/bin/bash

# include git completion if available
if [ -f $HOME/.bash/git-completion.bash ]; then
    . $HOME/.bash/git-completion.bash
fi

if [ -e "$HOME/.bash/prompt" ]; then
    source "$HOME/.bash/prompt"
fi

RC_FILE="~/.bashrc"
if [ -f "$HOME/.shell/common" ]; then
    source "$HOME/.shell/common"
fi

# shopt -s progcomp
#include custom bash setup
if [ -f $HOME/.bash_custom ]; then
    source $HOME/.bash_custom
fi
